include: package:very_good_analysis/analysis_options.5.1.0.yaml
analyzer:
  exclude:
    - build/**
linter:
  rules:
    file_names: false
    public_member_api_docs: false
    prefer_single_quotes: true
    always_use_package_imports: true
    empty_statements: true
    always_declare_return_types: true
    camel_case_extensions: true
    require_trailing_commas: true
    sort_constructors_first: false
    always_put_required_named_parameters_first: false
    unnecessary_lambdas: false
    non_constant_identifier_names: false
