name: cats_backend
description: An new Dart Frog application
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  crypto: ^3.0.3
  dart_frog: ^1.0.0
  dart_frog_auth: ^1.1.0
  dartz:
  firebase_dart: ^1.1.4
  jaguar_jwt: ^3.0.0
  mongo_dart: ^0.10.3

dev_dependencies:
  mocktail: ^1.0.0
  test: ^1.19.2
  very_good_analysis: ^5.1.0
