name: 🛠️ Pull Request CI
on: [push, workflow_dispatch]
jobs:
  drive:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dart-lang/setup-dart@v1
        with:
          channel: stable
          version: 3.5.3
      - run: dart --version
      - name: Dart Apply Fixes (if this fails, run `dart fix --apply` locally)
        run: dart fix --apply; git diff --exit-code
      - name: Dart Formatter (if this fails, run `dart format .` locally)
        run: dart format .; git diff --exit-code
      - name: Restore packages
        run: dart pub get
      - name: Dart Analyze
        run: dart analyze
      - name: Run tests without coverage
        run: dart test