name: 🛠️ Pull Request CI
on: [push, workflow_dispatch]
jobs:
  drive:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dart-lang/setup-dart@9a04e6d73cca37bd455e0608d7e5092f881fd603
        with:
          channel: stable
          version: 3.4.0
      - run: dart --version
      - name: Dart Apply Fixes (if this fails, run `dart fix --apply` locally)
        run: dart fix --apply; git diff --exit-code
      - name: Dart Apply Fixes (if this fails, run `dart fix --apply` locally)
        run: dart fix --apply; git diff --exit-code
      - name: Dart Formatter (if this fails, run `dart format .` locally)
        run: dart format .; git diff --exit-code
      - name: Restore packages
        run: dart pub get
#      - name: Dart Analyze
#        run: dart analyze
      - name: Run tests without coverage
        run: dart test